packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "esbuild"
  - "sharp"
  - "unrs-resolver"
allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: true
  unrs-resolver: true

overrides:
  'next>postcss': 8.5.26
  'next>sharp': 0.35.0
